### ISSUE TITLE
SwaggerUI (not found in project, manifest or registry)

### ISSUE THREAD

**Issue by fabiorsodre** [jiachengzhang1/SwaggerUI#11]
(@v1.7) pkg> add SwaggerUI
ERROR: The following package names could not be resolved: * SwaggerUI (not found in project, manifest or registry)

I'm using Julia v1.7.3 and Genie v4.18.2

**Comment by jiachengzhang1** [comment]
@fabiorsodre mb, it should be `add SwagUI`, I'll update the `readme` file, thanks for pointing this out
