### ISSUE TITLE
Join GenieFramework

### ISSUE THREAD

**Issue by essenciary** [jiachengzhang1/SwaggerUI#7]
Hi, 

We're currently setting up a dev hub around Genie and various packages working on top of it. Making all these awesome libraries easy to find and creating a documentation section that integrates all the packages, with integrated API search. 

Would you like to bring SwagUI into the GenieFramwork Github organisation and/or integrate it on GenieFramework.com?

Adrian

**Comment by jiachengzhang1** [comment]
@essenciary Sure, I'd like to do that. What do you need me to do?

**Comment by essenciary** [comment]
Awesome! I'm thinking: 

1/ I'll add you as a member to the GenieFramework organisation 
2/ add SwagUI to the GenieFramework org 
3/ add SwagUI docs to the main docs hub https://genieframework.com/docs/ 
4/ add it to Genie plugins (libraries) on home https://genieframework.com

What do you think?

**Comment by jiachengzhang1** [comment]
@essenciary yeah, that sounds good to me, I can work on these

**Comment by essenciary** [comment]
@jiachengzhang1 Great, I've sent you an invite to the GenieFramework organisation - can you please check?

**Comment by jiachengzhang1** [comment]
@essenciary thanks, just accepted it. I tried to transfer the repo, but I don't have permission to create repo in GenieFramework

**Comment by essenciary** [comment]
Sorry, that was quite tricky to figure out on github :) Should be fine now.

**Comment by essenciary** [comment]
@jiachengzhang1 It worked, welcome to GF org 🥳
